eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:instead
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5434/transactions_db
    username: admin
    password: root
  flyway:
    locations: classpath:migration
  kafka:
    consumer:
      group-id: "237e9877-e79b"

server:
  port: 8071

topic_of_accounts:
  name: transaction_of_accounts.reg

topic_refill_balance:
  name: transaction_refill_balance.reg



management:
  tracing:
    sampling:
      probability: 1.0
