eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: transaction-service
  config:
    import: optional:configserver:instead
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    locations: classpath:migration
  kafka:
    consumer:
      group-id: "237e9877-e79b"


topic_of_accounts:
  name: transaction_of_accounts.reg

topic_refill_or_write-off_balance:
  name: transaction_refill_or_write-off_balance.reg



management:
  tracing:
    sampling:
      probability: 1.0
