eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

server:
  port: 8222

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:instead

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8484/auth/realms/FinTechFlow

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account/**

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**


management:
  tracing:
    sampling:
      probability: 1.0


