eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

server:
  port: 8222

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:instead

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8484/auth/realms/FinTechFlow

  cloud:
    gateway:
      routes:



management:
  tracing:
    sampling:
      probability: 1.0


