eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: account-service
  config:
    import: optional:configserver:instead
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/accounts_db
    username: admin
    password: root
  flyway:
    locations: classpath:migration
  kafka:
    bootstrap-servers: localhost:9092
    auto-offset-reset: earliest



topic_of_accounts:
  name: transaction_of_accounts.reg

topic_refill_or_write-off_balance:
  name: transaction_refill_or_write-off_balance.reg



management:
  tracing:
    sampling:
      probability: 1.0
