eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:instead
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9092


topic:
  name: t.user.reg

  flyway:
    locations: classpath:migration
#transaction.reg

management:
  tracing:
    sampling:
      probability: 1.0
